package com.softprodigy.ballerapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFF8ecdff)
val Purple500 = Color(0xFF1977f3)
val Purple700 = Color(0xFF1977f3)
val Teal200 = Color(0xFF1977f3)

val Yellow200 = Color(0xFFf3ec92)
val Yellow500 = Color(0xFFe9da1c)
val Yellow700 = Color(0xFFFF923D)
val Teal300 = Color(0xFFa9ee59)

val heading1Color=Color(0xFF373737)
//val heading1Color=Color(0xFF373737)
val heading2Color=Color(0xFF666666)
val heading2OnDarkColor=Color(0xFFFFFFFF)

val heading3Color= Color(0xFFE4EBF0)

val md_theme_light_primary = Color(0xFF3E4FE5)
val md_theme_light_onPrimary =Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF1066FF)
val md_theme_light_onPrimaryContainer = Color(0xFF170066)
val md_theme_light_secondary = Color(0xFF5f5c71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe5dff9)
val md_theme_light_onSecondaryContainer = Color(0xFF1b192b)
val md_theme_light_tertiary = Color(0xFF7c5265)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd8e8)
val md_theme_light_onTertiaryContainer = Color(0xFF301021)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFffffff)
val md_theme_light_onBackground = Color(0xFF353131)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF1c1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe5e0ec)
val md_theme_light_onSurfaceVariant = Color(0xFF48454e)
val md_theme_light_outline = Color(0xFF797680)
val md_theme_light_inverseOnSurface = Color(0xFFf4eff4)
val md_theme_light_inverseSurface = Color(0xFF313033)

val md_theme_dark_primary = Color(0xFFc9bfff)
val md_theme_dark_onPrimary = Color(0xFF2a009f)
val md_theme_dark_primaryContainer = Color(0xFF3e00de)
val md_theme_dark_onPrimaryContainer = Color(0xFFe6deff)
val md_theme_dark_secondary = Color(0xFFc9c3dc)
val md_theme_dark_onSecondary = Color(0xFF312e42)
val md_theme_dark_secondaryContainer = Color(0xFF474459)
val md_theme_dark_onSecondaryContainer = Color(0xFFe5dff9)
val md_theme_dark_tertiary = Color(0xFFecb9ce)
val md_theme_dark_onTertiary = Color(0xFF482536)
val md_theme_dark_tertiaryContainer = Color(0xFF613b4d)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8e8)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1b1f)
val md_theme_dark_onBackground = Color(0xFFe5e1e5)
val md_theme_dark_surface = Color(0xFF1c1b1f)
val md_theme_dark_onSurface = Color(0xFFe5e1e5)
val md_theme_dark_surfaceVariant = Color(0xFF48454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc9c5d0)
val md_theme_dark_outline = Color(0xFF928f99)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe5e1e5)

val seed = Color(0xFF4f0fff)
val error = Color(0xFFba1b1b)

val ol_field_border_focused = Color(0xFF3E4FE5)
val ol_field_border_unfocused = Color(0xFF353131)
val ol_field_border_error = Color(0xFFED7E49)

val text_field_label =  Color(0x80FFFFFF)
val text_field_indicator =  Color(0xB3FFFFFF)

val spiner_popup_background = Color(0XFF363443)
val spiner_popup_border = Color(0x26FFFFFF)

val button_background_enable = Color(0xFF17191B)
val button_background_disable = Color(0xFFE4EBF0)
val button_text_enable = Color(0xFFFFFFFF)
val button_text_disable = Color(0xBF58636B)
val ColorBWBlack= Color(0xFF17191B)
val ColorBWGrayMedium= Color(0xFF58636B)
val ColorBWGrayBorder= Color(0xFFE4EBF0)
val ColorBWGrayLight= Color(0xFF8A9BA8)
val ColorPrimaryTransparent= Color(0x1A0177C1)
val ColorMainPrimary = Color(0xFF0177C1)
val ColorPrimaryOrange = Color(0xFFFF923D)


